name: Semgrep

on:
  # Scan changed files in PRs, block on new issues only (existing issues ignored)
  pull_request: {}

  # Scan all files on branches, block on any issues
  push:
    branches: ["master", "main"]

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source
      - uses: actions/checkout@v4

      - run: semgrep ci
        # run: semgrep scan --sarif --output=semgrep.sarif
        env:
          # more rules at semgrep.dev/explore
          SEMGREP_RULES: >-
            .semgrep
            p/security-audit
            p/secrets
            p/supply-chain
            p/owasp-top-ten
            p/ci
            p/r2c-ci
            p/docker
            p/dockerfile
            p/golang
            p/semgrep-go-correctness
            p/insecure-transport
            p/javascript
            p/kubernetes
            p/terraform
          SEMGREP_SEND_METRICS: off
          SEMGREP_TIMEOUT: 1800
          #SEMGREP_BASELINE_REF: master
