name: Semgrep

on:
  # Scan changed files in PRs, block on new issues only (existing issues ignored)
  pull_request: {}

  # Scan all files on branches, block on any issues
  push:
    branches: ["master", "main"]

jobs:
  semgrep:
    uses: payrails/actions/.github/workflows/reusable-semgrep.yaml@main
    with:
      extra_rules: p/swift